version: '3.8'

services:
  backend-main:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    container_name: pxg-backend-main

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend-main
    container_name: pxg-frontend
